name: EAS - Update Production Build

on:
    workflow_dispatch:

env:
    API_URL: ${{ secrets.PROD_API_URL }}
    APP_VARIANT: PRODUCTION

jobs:
    eas_update_production:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: npm install

            - name: Create update
              run: eas update --channel production --non-interactive --message "${{ env.VERSION }}-staging"
