name: EAS Update Staging

on:
    workflow_dispatch:

env:
    API_URL: ${{ secrets.PROD_API_URL }}
    ENVIRONMENT: PREVIEW

jobs:
    eas_update_staging:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Verify on staging branch
              if: github.ref == 'refs/heads/staging'
              run: echo "This workflow can only run on the staging branch"

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: npm install

            - name: Create update
              run: eas update --channel preview --platform ios --auto --non-interactive
