name: Staging Branch Protection

on:
    pull_request:
        branches:
            - staging

jobs:
    check-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch
              run: |
                  if [[ ${GITHUB_HEAD_REF} != development ]]; 
                  then
                    echo "Error: Pull request must come from 'development' branch"
                    exit 1
                  fi
