name: Version Check

on:
    pull_request:
        branches:
            - main
            - development
            - staging
jobs:
    check_version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source branch
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Get source branch version
              id: source_version
              run: |
                  echo "Fetching package.json version from source branch..."
                  source_version=$(jq -r .version < package.json)
                  echo "source_version=$source_version" >> $GITHUB_ENV
            - name: Checkout target branch
              run: |
                  git fetch origin ${{ github.base_ref }} --depth=1
                  git checkout ${{ github.base_ref }}
            - name: Get target branch version
              id: target_version
              run: |
                  echo "Fetching package.json version from target branch..."
                  target_version=$(jq -r .version < package.json)
                  echo "target_version=$target_version" >> $GITHUB_ENV
            - name: Compare package.json versions
              run: |
                  echo "Comparing source and target versions..."
                  echo "Source version: ${{ env.source_version }}"
                  echo "Target version: ${{ env.target_version }}"
                  if [ "$(npx semver ${{ env.source_version }} -r '>${{ env.target_version }}')" == "" ]; then
                    echo "The version in the source branch is not higher than the target branch."
                    exit 1
                  else
                    echo "The version in the source branch is higher than the target branch."
                  fi
            - name: Success
              if: success()
              run: echo "Version check passed!"
